# Text for figure labels
# Moved from internal.R and exported 20200204
# Moved from diffplot.R and changed expression() to quote() 20230617

cplab <- list(
  Zc = quote(italic(Z)[C]),
  DZc = quote(Delta*italic(Z)[C]),
  nO2 = quote(italic(n)[O[2]]),
  DnO2 = quote(Delta*italic(n)[O[2]]),
  nH2O = quote(italic(n)[H[2]*O]),
  DnH2O = quote(Delta*italic(n)[H[2]*O]),
  logfO2 = quote(log~italic("f")[O[2]]),
  logaH2O = quote(log~italic("a")[H[2]*O]),
  nC = quote(italic(n)[C] * "/AA"),
  nH = quote(italic(n)[H] * "/AA"),
  nN = quote(italic(n)[N] * "/AA"),
  nO = quote(italic(n)[O] * "/AA"),
  nS = quote(italic(n)[S] * "/AA"),
  DnC = quote(Delta*italic(n)[C] * "/AA"),
  DnH = quote(Delta*italic(n)[H] * "/AA"),
  DnN = quote(Delta*italic(n)[N] * "/AA"),
  DnO = quote(Delta*italic(n)[O] * "/AA"),
  DnS = quote(Delta*italic(n)[S] * "/AA"),
  V0 = quote("Volume per residue (cm" ^ 3 ~ "mol" ^ -1 * ")"),
  pV0 = quote("Volume per protein (cm" ^ 3 ~ "mol" ^ -1 * ")"),
  DV0 = quote(Delta * "V per residue (cm" ^ 3 ~ "mol" ^ -1 * ")"),
  DV0 = quote(Delta * "V per protein (cm" ^ 3 ~ "mol" ^ -1 * ")"),
  nAA = quote(italic(n)[AA]),
  DnAA = quote(Delta*italic(n)[AA]),
  GRAVY = "GRAVY",
  DGRAVY = quote(Delta*"GRAVY"),
  pI = "pI",
  DpI = quote(Delta*"pI"),
  MW = quote("MW per residue"),
  DMW = quote(Delta * "MW per residue"),
  pMW = quote("MW per protein"),
  DpMW = quote(Delta * "MW per protein"),
  plength = "Protein length",
  H_C = "H/C",
  HC = "H/C",
  N_C = "N/C",
  NC = "N/C",
  O_C = "O/C",
  OC = "O/C",
  S_C = "S/C",
  SC = "S/C"
)
